[product]
name = "@villagekit/baby-learning-tower"
label = "Baby Learning Tower"
description = "This adjustable learning tower provides a safe and sturdy platform for young children to stand on, enouraging your kids to play, learn, and assist you."
tags = [
  'furniture',
  'kid'
]
type = "kit"
exports = "./baby-learning-tower.ts"
