[product]
name = "@villagekit/side-table"
label = "Side Table"
description = "A trusty furniture companion. Situated next to a couch or bed, the side table helps keep everything you need within easy reach."
tags = [
  'Furniture',
  'table',
  'storage',
  'bedroom'
]
type = "kit"
exports = "./side-table.ts"
