[product]
name = "@villagekit/bike-rack"
label = "Bike rack"
description = "Vertical bike rack provides a sturdy, reliable, and efficient solution for bike storage in a garage."
tags = [
  'furniture',
  'bicycle',
  'storage'
]
type = "kit"
exports = "./bike-rack.ts"
