[product]
name = "@villagekit/makers-desk"
label = "Makers Desk"
description = "This modular workspace features a spacious work surface and an elevated shelf for additional storage."
tags = [
  'furniture',
  'desk',
  'garage'
]
type = "kit"
exports = "./makers-desk.ts"
