[product]
name = "@villagekit/ladder-shelf"
label = "Ladder shelf"
description = "Modular cabinet featuring multiple shelves for organized storage."
tags = [
  'furniture',
  'storage'
]
type = "kit"
exports = "./ladder-shelf.ts"
