[product]
name = "@villagekit/work-table"
label = "Work Table"
description = "A spacious working table. Ideal for arts, trades, or simply adding extra bench space."
tags = [
  'furniture',
  'desk',
  'garage',
  'office',
  'table',
  'workbench'
]
type = "kit"
exports = "./work-table.ts"
