[product]
name = "@villagekit/garage-workbench"
label = "Garage Workbench"
description = "A robust workbench featuring ample storage space with multiple drawers. Ideal for organizing tools and supplies, making it a practical addition to any workshop or garage."
tags = [
  'furniture',
  'garage',
  'workbench',
  'storage'
]
type = "kit"
exports = "./garage-workbench.ts"
